// Code generated by mockery v2.53.6. DO NOT EDIT.

package domain

import (
	context "context"

	domain "github.com/jdgonzalez907/saas-api/internal/auth/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockAuthOTPRepository is an autogenerated mock type for the AuthOTPRepository type
type MockAuthOTPRepository struct {
	mock.Mock
}

type MockAuthOTPRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthOTPRepository) EXPECT() *MockAuthOTPRepository_Expecter {
	return &MockAuthOTPRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, otp
func (_m *MockAuthOTPRepository) Create(ctx context.Context, otp *domain.AuthOTP) error {
	ret := _m.Called(ctx, otp)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.AuthOTP) error); ok {
		r0 = rf(ctx, otp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthOTPRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAuthOTPRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - otp *domain.AuthOTP
func (_e *MockAuthOTPRepository_Expecter) Create(ctx interface{}, otp interface{}) *MockAuthOTPRepository_Create_Call {
	return &MockAuthOTPRepository_Create_Call{Call: _e.mock.On("Create", ctx, otp)}
}

func (_c *MockAuthOTPRepository_Create_Call) Run(run func(ctx context.Context, otp *domain.AuthOTP)) *MockAuthOTPRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.AuthOTP))
	})
	return _c
}

func (_c *MockAuthOTPRepository_Create_Call) Return(_a0 error) *MockAuthOTPRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthOTPRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.AuthOTP) error) *MockAuthOTPRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByPhoneNumber provides a mock function with given fields: ctx, phoneNumber
func (_m *MockAuthOTPRepository) FindByPhoneNumber(ctx context.Context, phoneNumber string) (*domain.AuthOTP, error) {
	ret := _m.Called(ctx, phoneNumber)

	if len(ret) == 0 {
		panic("no return value specified for FindByPhoneNumber")
	}

	var r0 *domain.AuthOTP
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.AuthOTP, error)); ok {
		return rf(ctx, phoneNumber)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.AuthOTP); ok {
		r0 = rf(ctx, phoneNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AuthOTP)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, phoneNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthOTPRepository_FindByPhoneNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByPhoneNumber'
type MockAuthOTPRepository_FindByPhoneNumber_Call struct {
	*mock.Call
}

// FindByPhoneNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - phoneNumber string
func (_e *MockAuthOTPRepository_Expecter) FindByPhoneNumber(ctx interface{}, phoneNumber interface{}) *MockAuthOTPRepository_FindByPhoneNumber_Call {
	return &MockAuthOTPRepository_FindByPhoneNumber_Call{Call: _e.mock.On("FindByPhoneNumber", ctx, phoneNumber)}
}

func (_c *MockAuthOTPRepository_FindByPhoneNumber_Call) Run(run func(ctx context.Context, phoneNumber string)) *MockAuthOTPRepository_FindByPhoneNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthOTPRepository_FindByPhoneNumber_Call) Return(_a0 *domain.AuthOTP, _a1 error) *MockAuthOTPRepository_FindByPhoneNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthOTPRepository_FindByPhoneNumber_Call) RunAndReturn(run func(context.Context, string) (*domain.AuthOTP, error)) *MockAuthOTPRepository_FindByPhoneNumber_Call {
	_c.Call.Return(run)
	return _c
}

// FindBySessionID provides a mock function with given fields: ctx, sessionID
func (_m *MockAuthOTPRepository) FindBySessionID(ctx context.Context, sessionID string) (*domain.AuthOTP, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for FindBySessionID")
	}

	var r0 *domain.AuthOTP
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.AuthOTP, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.AuthOTP); ok {
		r0 = rf(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AuthOTP)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthOTPRepository_FindBySessionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBySessionID'
type MockAuthOTPRepository_FindBySessionID_Call struct {
	*mock.Call
}

// FindBySessionID is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockAuthOTPRepository_Expecter) FindBySessionID(ctx interface{}, sessionID interface{}) *MockAuthOTPRepository_FindBySessionID_Call {
	return &MockAuthOTPRepository_FindBySessionID_Call{Call: _e.mock.On("FindBySessionID", ctx, sessionID)}
}

func (_c *MockAuthOTPRepository_FindBySessionID_Call) Run(run func(ctx context.Context, sessionID string)) *MockAuthOTPRepository_FindBySessionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthOTPRepository_FindBySessionID_Call) Return(_a0 *domain.AuthOTP, _a1 error) *MockAuthOTPRepository_FindBySessionID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthOTPRepository_FindBySessionID_Call) RunAndReturn(run func(context.Context, string) (*domain.AuthOTP, error)) *MockAuthOTPRepository_FindBySessionID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, otp
func (_m *MockAuthOTPRepository) Update(ctx context.Context, otp *domain.AuthOTP) error {
	ret := _m.Called(ctx, otp)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.AuthOTP) error); ok {
		r0 = rf(ctx, otp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthOTPRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockAuthOTPRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - otp *domain.AuthOTP
func (_e *MockAuthOTPRepository_Expecter) Update(ctx interface{}, otp interface{}) *MockAuthOTPRepository_Update_Call {
	return &MockAuthOTPRepository_Update_Call{Call: _e.mock.On("Update", ctx, otp)}
}

func (_c *MockAuthOTPRepository_Update_Call) Run(run func(ctx context.Context, otp *domain.AuthOTP)) *MockAuthOTPRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.AuthOTP))
	})
	return _c
}

func (_c *MockAuthOTPRepository_Update_Call) Return(_a0 error) *MockAuthOTPRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthOTPRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.AuthOTP) error) *MockAuthOTPRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthOTPRepository creates a new instance of MockAuthOTPRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthOTPRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthOTPRepository {
	mock := &MockAuthOTPRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
