// Code generated by mockery v2.53.6. DO NOT EDIT.

package domain

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockOTPSenderRepository is an autogenerated mock type for the OTPSenderRepository type
type MockOTPSenderRepository struct {
	mock.Mock
}

type MockOTPSenderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOTPSenderRepository) EXPECT() *MockOTPSenderRepository_Expecter {
	return &MockOTPSenderRepository_Expecter{mock: &_m.Mock}
}

// SendOTP provides a mock function with given fields: ctx, phoneNumber, code
func (_m *MockOTPSenderRepository) SendOTP(ctx context.Context, phoneNumber string, code string) error {
	ret := _m.Called(ctx, phoneNumber, code)

	if len(ret) == 0 {
		panic("no return value specified for SendOTP")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, phoneNumber, code)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOTPSenderRepository_SendOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendOTP'
type MockOTPSenderRepository_SendOTP_Call struct {
	*mock.Call
}

// SendOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - phoneNumber string
//   - code string
func (_e *MockOTPSenderRepository_Expecter) SendOTP(ctx interface{}, phoneNumber interface{}, code interface{}) *MockOTPSenderRepository_SendOTP_Call {
	return &MockOTPSenderRepository_SendOTP_Call{Call: _e.mock.On("SendOTP", ctx, phoneNumber, code)}
}

func (_c *MockOTPSenderRepository_SendOTP_Call) Run(run func(ctx context.Context, phoneNumber string, code string)) *MockOTPSenderRepository_SendOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockOTPSenderRepository_SendOTP_Call) Return(_a0 error) *MockOTPSenderRepository_SendOTP_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOTPSenderRepository_SendOTP_Call) RunAndReturn(run func(context.Context, string, string) error) *MockOTPSenderRepository_SendOTP_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOTPSenderRepository creates a new instance of MockOTPSenderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOTPSenderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOTPSenderRepository {
	mock := &MockOTPSenderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
