// Code generated by mockery v2.53.6. DO NOT EDIT.

package domain

import (
	context "context"

	domain "github.com/jdgonzalez907/saas-api/internal/auth/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockOTPSenderRepository is an autogenerated mock type for the OTPSenderRepository type
type MockOTPSenderRepository struct {
	mock.Mock
}

type MockOTPSenderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOTPSenderRepository) EXPECT() *MockOTPSenderRepository_Expecter {
	return &MockOTPSenderRepository_Expecter{mock: &_m.Mock}
}

// Send provides a mock function with given fields: ctx, otp
func (_m *MockOTPSenderRepository) Send(ctx context.Context, otp *domain.AuthOTP) error {
	ret := _m.Called(ctx, otp)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.AuthOTP) error); ok {
		r0 = rf(ctx, otp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOTPSenderRepository_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockOTPSenderRepository_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - otp *domain.AuthOTP
func (_e *MockOTPSenderRepository_Expecter) Send(ctx interface{}, otp interface{}) *MockOTPSenderRepository_Send_Call {
	return &MockOTPSenderRepository_Send_Call{Call: _e.mock.On("Send", ctx, otp)}
}

func (_c *MockOTPSenderRepository_Send_Call) Run(run func(ctx context.Context, otp *domain.AuthOTP)) *MockOTPSenderRepository_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.AuthOTP))
	})
	return _c
}

func (_c *MockOTPSenderRepository_Send_Call) Return(_a0 error) *MockOTPSenderRepository_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOTPSenderRepository_Send_Call) RunAndReturn(run func(context.Context, *domain.AuthOTP) error) *MockOTPSenderRepository_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOTPSenderRepository creates a new instance of MockOTPSenderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOTPSenderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOTPSenderRepository {
	mock := &MockOTPSenderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
