// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Post struct {
	ID           int64
	Title        string
	Content      []byte
	Status       string
	AuthorID     int64
	LastEditorID int64
	PublishedAt  pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	DeletedBy    pgtype.Int8
}

type User struct {
	ID                   int64
	IdentificationType   string
	IdentificationNumber string
	FirstName            string
	LastName             string
	BirthDate            pgtype.Date
	Address              []byte
	PhoneCountryCode     string
	PhoneNumber          string
	Email                pgtype.Text
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	DeletedAt            pgtype.Timestamptz
}
