run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - gci
    - revive

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(jdgonzalez907/saas-api)
    custom-order: true

issues:
  exclude-dirs:
    - internal/postgres
    - internal/shared/postgres
    - mocks
