with-expecter: true
tags: "test"
dir: "mocks/{{.PackageName}}"
keeptree: false
resolve-type-alias: false
disable-version-string: true
issue-845-fix: true

packages:
  jdgonzalez907/saas-api/internal/users/domain:
    config:
      all: true
  jdgonzalez907/saas-api/internal/users/application:
    config:
      all: true
