// Code generated by mockery v2.53.6. DO NOT EDIT.

package domain

import (
	context "context"

	domain "github.com/jdgonzalez907/saas-api/internal/posts/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockAutorRepository is an autogenerated mock type for the AutorRepository type
type MockAutorRepository struct {
	mock.Mock
}

type MockAutorRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAutorRepository) EXPECT() *MockAutorRepository_Expecter {
	return &MockAutorRepository_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockAutorRepository) FindByID(ctx context.Context, id int64) (*domain.Autor, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Autor
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*domain.Autor, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *domain.Autor); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Autor)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAutorRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockAutorRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockAutorRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockAutorRepository_FindByID_Call {
	return &MockAutorRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockAutorRepository_FindByID_Call) Run(run func(ctx context.Context, id int64)) *MockAutorRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockAutorRepository_FindByID_Call) Return(_a0 *domain.Autor, _a1 error) *MockAutorRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAutorRepository_FindByID_Call) RunAndReturn(run func(context.Context, int64) (*domain.Autor, error)) *MockAutorRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAutorRepository creates a new instance of MockAutorRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAutorRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAutorRepository {
	mock := &MockAutorRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
