// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_domain

import (
	"context"

	"github.com/jdgonzalez907/saas-api/internal/posts/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPostRepository creates a new instance of MockPostRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPostRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPostRepository {
	mock := &MockPostRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPostRepository is an autogenerated mock type for the PostRepository type
type MockPostRepository struct {
	mock.Mock
}

type MockPostRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPostRepository) EXPECT() *MockPostRepository_Expecter {
	return &MockPostRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockPostRepository
func (_mock *MockPostRepository) Create(ctx context.Context, post *domain.Post) error {
	ret := _mock.Called(ctx, post)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Post) error); ok {
		r0 = returnFunc(ctx, post)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPostRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPostRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - post *domain.Post
func (_e *MockPostRepository_Expecter) Create(ctx any, post any) *MockPostRepository_Create_Call {
	return &MockPostRepository_Create_Call{Call: _e.mock.On("Create", ctx, post)}
}

func (_c *MockPostRepository_Create_Call) Run(run func(ctx context.Context, post *domain.Post)) *MockPostRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Post
		if args[1] != nil {
			arg1 = args[1].(*domain.Post)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostRepository_Create_Call) Return(err error) *MockPostRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPostRepository_Create_Call) RunAndReturn(run func(ctx context.Context, post *domain.Post) error) *MockPostRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockPostRepository
func (_mock *MockPostRepository) FindByID(ctx context.Context, id int64) (*domain.Post, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Post
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*domain.Post, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *domain.Post); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Post)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPostRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockPostRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockPostRepository_Expecter) FindByID(ctx any, id any) *MockPostRepository_FindByID_Call {
	return &MockPostRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockPostRepository_FindByID_Call) Run(run func(ctx context.Context, id int64)) *MockPostRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostRepository_FindByID_Call) Return(post *domain.Post, err error) *MockPostRepository_FindByID_Call {
	_c.Call.Return(post, err)
	return _c
}

func (_c *MockPostRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (*domain.Post, error)) *MockPostRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindBySlug provides a mock function for the type MockPostRepository
func (_mock *MockPostRepository) FindBySlug(ctx context.Context, slug string) (*domain.Post, error) {
	ret := _mock.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for FindBySlug")
	}

	var r0 *domain.Post
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Post, error)); ok {
		return returnFunc(ctx, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Post); ok {
		r0 = returnFunc(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Post)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPostRepository_FindBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBySlug'
type MockPostRepository_FindBySlug_Call struct {
	*mock.Call
}

// FindBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockPostRepository_Expecter) FindBySlug(ctx any, slug any) *MockPostRepository_FindBySlug_Call {
	return &MockPostRepository_FindBySlug_Call{Call: _e.mock.On("FindBySlug", ctx, slug)}
}

func (_c *MockPostRepository_FindBySlug_Call) Run(run func(ctx context.Context, slug string)) *MockPostRepository_FindBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostRepository_FindBySlug_Call) Return(post *domain.Post, err error) *MockPostRepository_FindBySlug_Call {
	_c.Call.Return(post, err)
	return _c
}

func (_c *MockPostRepository_FindBySlug_Call) RunAndReturn(run func(ctx context.Context, slug string) (*domain.Post, error)) *MockPostRepository_FindBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockPostRepository
func (_mock *MockPostRepository) Update(ctx context.Context, post *domain.Post) error {
	ret := _mock.Called(ctx, post)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Post) error); ok {
		r0 = returnFunc(ctx, post)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPostRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockPostRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - post *domain.Post
func (_e *MockPostRepository_Expecter) Update(ctx any, post any) *MockPostRepository_Update_Call {
	return &MockPostRepository_Update_Call{Call: _e.mock.On("Update", ctx, post)}
}

func (_c *MockPostRepository_Update_Call) Run(run func(ctx context.Context, post *domain.Post)) *MockPostRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Post
		if args[1] != nil {
			arg1 = args[1].(*domain.Post)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostRepository_Update_Call) Return(err error) *MockPostRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPostRepository_Update_Call) RunAndReturn(run func(ctx context.Context, post *domain.Post) error) *MockPostRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
