// Code generated by mockery v2.53.6. DO NOT EDIT.

package application

import (
	context "context"

	domain "github.com/jdgonzalez907/saas-api/internal/posts/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockCreatePost is an autogenerated mock type for the CreatePost type
type MockCreatePost struct {
	mock.Mock
}

type MockCreatePost_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreatePost) EXPECT() *MockCreatePost_Expecter {
	return &MockCreatePost_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, title, slug, cover, content, status, authorID
func (_m *MockCreatePost) Execute(ctx context.Context, title string, slug string, cover string, content []domain.Block, status domain.PostStatus, authorID int64) (*domain.Post, error) {
	ret := _m.Called(ctx, title, slug, cover, content, status, authorID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *domain.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, []domain.Block, domain.PostStatus, int64) (*domain.Post, error)); ok {
		return rf(ctx, title, slug, cover, content, status, authorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, []domain.Block, domain.PostStatus, int64) *domain.Post); ok {
		r0 = rf(ctx, title, slug, cover, content, status, authorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, []domain.Block, domain.PostStatus, int64) error); ok {
		r1 = rf(ctx, title, slug, cover, content, status, authorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCreatePost_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockCreatePost_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - title string
//   - slug string
//   - cover string
//   - content []domain.Block
//   - status domain.PostStatus
//   - authorID int64
func (_e *MockCreatePost_Expecter) Execute(ctx interface{}, title interface{}, slug interface{}, cover interface{}, content interface{}, status interface{}, authorID interface{}) *MockCreatePost_Execute_Call {
	return &MockCreatePost_Execute_Call{Call: _e.mock.On("Execute", ctx, title, slug, cover, content, status, authorID)}
}

func (_c *MockCreatePost_Execute_Call) Run(run func(ctx context.Context, title string, slug string, cover string, content []domain.Block, status domain.PostStatus, authorID int64)) *MockCreatePost_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].([]domain.Block), args[5].(domain.PostStatus), args[6].(int64))
	})
	return _c
}

func (_c *MockCreatePost_Execute_Call) Return(_a0 *domain.Post, _a1 error) *MockCreatePost_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCreatePost_Execute_Call) RunAndReturn(run func(context.Context, string, string, string, []domain.Block, domain.PostStatus, int64) (*domain.Post, error)) *MockCreatePost_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCreatePost creates a new instance of MockCreatePost. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreatePost(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreatePost {
	mock := &MockCreatePost{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
