// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_application

import (
	"context"

	"github.com/jdgonzalez907/saas-api/internal/posts/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFindPostBySlug creates a new instance of MockFindPostBySlug. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFindPostBySlug(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFindPostBySlug {
	mock := &MockFindPostBySlug{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFindPostBySlug is an autogenerated mock type for the FindPostBySlug type
type MockFindPostBySlug struct {
	mock.Mock
}

type MockFindPostBySlug_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFindPostBySlug) EXPECT() *MockFindPostBySlug_Expecter {
	return &MockFindPostBySlug_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockFindPostBySlug
func (_mock *MockFindPostBySlug) Execute(ctx context.Context, slug string) (*domain.Post, error) {
	ret := _mock.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *domain.Post
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Post, error)); ok {
		return returnFunc(ctx, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Post); ok {
		r0 = returnFunc(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Post)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFindPostBySlug_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockFindPostBySlug_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockFindPostBySlug_Expecter) Execute(ctx any, slug any) *MockFindPostBySlug_Execute_Call {
	return &MockFindPostBySlug_Execute_Call{Call: _e.mock.On("Execute", ctx, slug)}
}

func (_c *MockFindPostBySlug_Execute_Call) Run(run func(ctx context.Context, slug string)) *MockFindPostBySlug_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFindPostBySlug_Execute_Call) Return(post *domain.Post, err error) *MockFindPostBySlug_Execute_Call {
	_c.Call.Return(post, err)
	return _c
}

func (_c *MockFindPostBySlug_Execute_Call) RunAndReturn(run func(ctx context.Context, slug string) (*domain.Post, error)) *MockFindPostBySlug_Execute_Call {
	_c.Call.Return(run)
	return _c
}
