// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_application

import (
	"context"

	"github.com/jdgonzalez907/saas-api/internal/posts/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUpdateContent creates a new instance of MockUpdateContent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdateContent(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdateContent {
	mock := &MockUpdateContent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUpdateContent is an autogenerated mock type for the UpdateContent type
type MockUpdateContent struct {
	mock.Mock
}

type MockUpdateContent_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdateContent) EXPECT() *MockUpdateContent_Expecter {
	return &MockUpdateContent_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockUpdateContent
func (_mock *MockUpdateContent) Execute(ctx context.Context, id int64, executedBy int64, title string, slug string, cover string, content []domain.Block, status domain.PostStatus) (*domain.Post, error) {
	ret := _mock.Called(ctx, id, executedBy, title, slug, cover, content, status)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *domain.Post
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, string, string, string, []domain.Block, domain.PostStatus) (*domain.Post, error)); ok {
		return returnFunc(ctx, id, executedBy, title, slug, cover, content, status)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, string, string, string, []domain.Block, domain.PostStatus) *domain.Post); ok {
		r0 = returnFunc(ctx, id, executedBy, title, slug, cover, content, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Post)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64, string, string, string, []domain.Block, domain.PostStatus) error); ok {
		r1 = returnFunc(ctx, id, executedBy, title, slug, cover, content, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUpdateContent_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockUpdateContent_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - executedBy int64
//   - title string
//   - slug string
//   - cover string
//   - content []domain.Block
//   - status domain.PostStatus
func (_e *MockUpdateContent_Expecter) Execute(ctx any, id any, executedBy any, title any, slug any, cover any, content any, status any) *MockUpdateContent_Execute_Call {
	return &MockUpdateContent_Execute_Call{Call: _e.mock.On("Execute", ctx, id, executedBy, title, slug, cover, content, status)}
}

func (_c *MockUpdateContent_Execute_Call) Run(run func(ctx context.Context, id int64, executedBy int64, title string, slug string, cover string, content []domain.Block, status domain.PostStatus)) *MockUpdateContent_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		var arg6 []domain.Block
		if args[6] != nil {
			arg6 = args[6].([]domain.Block)
		}
		var arg7 domain.PostStatus
		if args[7] != nil {
			arg7 = args[7].(domain.PostStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
			arg7,
		)
	})
	return _c
}

func (_c *MockUpdateContent_Execute_Call) Return(post *domain.Post, err error) *MockUpdateContent_Execute_Call {
	_c.Call.Return(post, err)
	return _c
}

func (_c *MockUpdateContent_Execute_Call) RunAndReturn(run func(ctx context.Context, id int64, executedBy int64, title string, slug string, cover string, content []domain.Block, status domain.PostStatus) (*domain.Post, error)) *MockUpdateContent_Execute_Call {
	_c.Call.Return(run)
	return _c
}
