// Code generated by mockery v2.53.6. DO NOT EDIT.

package application

import (
	context "context"

	domain "github.com/jdgonzalez907/saas-api/internal/posts/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockUpdateContent is an autogenerated mock type for the UpdateContent type
type MockUpdateContent struct {
	mock.Mock
}

type MockUpdateContent_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdateContent) EXPECT() *MockUpdateContent_Expecter {
	return &MockUpdateContent_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, id, executedBy, title, slug, cover, content, status
func (_m *MockUpdateContent) Execute(ctx context.Context, id int64, executedBy int64, title string, slug string, cover string, content []domain.Block, status domain.PostStatus) (*domain.Post, error) {
	ret := _m.Called(ctx, id, executedBy, title, slug, cover, content, status)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *domain.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, string, string, string, []domain.Block, domain.PostStatus) (*domain.Post, error)); ok {
		return rf(ctx, id, executedBy, title, slug, cover, content, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, string, string, string, []domain.Block, domain.PostStatus) *domain.Post); ok {
		r0 = rf(ctx, id, executedBy, title, slug, cover, content, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, string, string, string, []domain.Block, domain.PostStatus) error); ok {
		r1 = rf(ctx, id, executedBy, title, slug, cover, content, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpdateContent_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockUpdateContent_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - executedBy int64
//   - title string
//   - slug string
//   - cover string
//   - content []domain.Block
//   - status domain.PostStatus
func (_e *MockUpdateContent_Expecter) Execute(ctx interface{}, id interface{}, executedBy interface{}, title interface{}, slug interface{}, cover interface{}, content interface{}, status interface{}) *MockUpdateContent_Execute_Call {
	return &MockUpdateContent_Execute_Call{Call: _e.mock.On("Execute", ctx, id, executedBy, title, slug, cover, content, status)}
}

func (_c *MockUpdateContent_Execute_Call) Run(run func(ctx context.Context, id int64, executedBy int64, title string, slug string, cover string, content []domain.Block, status domain.PostStatus)) *MockUpdateContent_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(string), args[4].(string), args[5].(string), args[6].([]domain.Block), args[7].(domain.PostStatus))
	})
	return _c
}

func (_c *MockUpdateContent_Execute_Call) Return(_a0 *domain.Post, _a1 error) *MockUpdateContent_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpdateContent_Execute_Call) RunAndReturn(run func(context.Context, int64, int64, string, string, string, []domain.Block, domain.PostStatus) (*domain.Post, error)) *MockUpdateContent_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpdateContent creates a new instance of MockUpdateContent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdateContent(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdateContent {
	mock := &MockUpdateContent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
