// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID                   int64
	IdentificationType   string
	IdentificationNumber string
	FirstName            string
	LastName             string
	BirthDate            pgtype.Date
	Address              []byte
	PhoneCountryCode     string
	PhoneNumber          string
	Email                pgtype.Text
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	DeletedAt            pgtype.Timestamptz
}
