// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (
    title,
    content,
    status,
    author_id,
    last_editor_id,
    published_at,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type CreatePostParams struct {
	Title        string
	Content      []byte
	Status       string
	AuthorID     int64
	LastEditorID int64
	PublishedAt  pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (int64, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.Title,
		arg.Content,
		arg.Status,
		arg.AuthorID,
		arg.LastEditorID,
		arg.PublishedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deletePost = `-- name: DeletePost :exec
UPDATE posts SET
    deleted_at = NOW(),
    deleted_by = $2
WHERE id = $1 AND deleted_at IS NULL
`

type DeletePostParams struct {
	ID        int64
	DeletedBy pgtype.Int8
}

func (q *Queries) DeletePost(ctx context.Context, arg DeletePostParams) error {
	_, err := q.db.Exec(ctx, deletePost, arg.ID, arg.DeletedBy)
	return err
}

const findPostByID = `-- name: FindPostByID :one
SELECT id, title, content, status, author_id, last_editor_id, published_at, created_at, updated_at
FROM posts
WHERE id = $1 AND deleted_at IS NULL
`

type FindPostByIDRow struct {
	ID           int64
	Title        string
	Content      []byte
	Status       string
	AuthorID     int64
	LastEditorID int64
	PublishedAt  pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) FindPostByID(ctx context.Context, id int64) (FindPostByIDRow, error) {
	row := q.db.QueryRow(ctx, findPostByID, id)
	var i FindPostByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Status,
		&i.AuthorID,
		&i.LastEditorID,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findPostsPaginatedWithCursor = `-- name: FindPostsPaginatedWithCursor :many
SELECT id, title, content, status, author_id, last_editor_id, published_at, created_at, updated_at
FROM posts
WHERE status = $1 AND deleted_at IS NULL AND (
    ($4::timestamptz IS NOT NULL AND published_at < $4) OR 
    ($4::timestamptz IS NOT NULL AND published_at = $4 AND id < $2) OR
    ($4::timestamptz IS NULL AND id < $2)
)
ORDER BY published_at DESC, id DESC
LIMIT $3
`

type FindPostsPaginatedWithCursorParams struct {
	Status          string
	ID              int64
	Limit           int32
	LastPublishedAt pgtype.Timestamptz
}

type FindPostsPaginatedWithCursorRow struct {
	ID           int64
	Title        string
	Content      []byte
	Status       string
	AuthorID     int64
	LastEditorID int64
	PublishedAt  pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) FindPostsPaginatedWithCursor(ctx context.Context, arg FindPostsPaginatedWithCursorParams) ([]FindPostsPaginatedWithCursorRow, error) {
	rows, err := q.db.Query(ctx, findPostsPaginatedWithCursor,
		arg.Status,
		arg.ID,
		arg.Limit,
		arg.LastPublishedAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindPostsPaginatedWithCursorRow
	for rows.Next() {
		var i FindPostsPaginatedWithCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.AuthorID,
			&i.LastEditorID,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPostsPaginatedWithoutCursor = `-- name: FindPostsPaginatedWithoutCursor :many
SELECT id, title, content, status, author_id, last_editor_id, published_at, created_at, updated_at
FROM posts
WHERE status = $1 AND deleted_at IS NULL
ORDER BY published_at DESC, id DESC
LIMIT $2
`

type FindPostsPaginatedWithoutCursorParams struct {
	Status string
	Limit  int32
}

type FindPostsPaginatedWithoutCursorRow struct {
	ID           int64
	Title        string
	Content      []byte
	Status       string
	AuthorID     int64
	LastEditorID int64
	PublishedAt  pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) FindPostsPaginatedWithoutCursor(ctx context.Context, arg FindPostsPaginatedWithoutCursorParams) ([]FindPostsPaginatedWithoutCursorRow, error) {
	rows, err := q.db.Query(ctx, findPostsPaginatedWithoutCursor, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindPostsPaginatedWithoutCursorRow
	for rows.Next() {
		var i FindPostsPaginatedWithoutCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.AuthorID,
			&i.LastEditorID,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePost = `-- name: UpdatePost :exec
UPDATE posts SET
    title = $1,
    content = $2,
    status = $3,
    author_id = $4,
    last_editor_id = $5,
    published_at = $6,
    updated_at = $7
WHERE id = $8 AND deleted_at IS NULL
`

type UpdatePostParams struct {
	Title        string
	Content      []byte
	Status       string
	AuthorID     int64
	LastEditorID int64
	PublishedAt  pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	ID           int64
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) error {
	_, err := q.db.Exec(ctx, updatePost,
		arg.Title,
		arg.Content,
		arg.Status,
		arg.AuthorID,
		arg.LastEditorID,
		arg.PublishedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
