// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    identification_type,
    identification_number,
    first_name,
    last_name,
    birth_date,
    address,
    phone_country_code,
    phone_number,
    email,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id
`

type CreateUserParams struct {
	IdentificationType   string
	IdentificationNumber string
	FirstName            string
	LastName             string
	BirthDate            pgtype.Date
	Address              []byte
	PhoneCountryCode     string
	PhoneNumber          string
	Email                pgtype.Text
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.IdentificationType,
		arg.IdentificationNumber,
		arg.FirstName,
		arg.LastName,
		arg.BirthDate,
		arg.Address,
		arg.PhoneCountryCode,
		arg.PhoneNumber,
		arg.Email,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE users SET 
    deleted_at = NOW(), 
    updated_at = NOW() 
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT 
    id, identification_type, identification_number, first_name, last_name, 
    birth_date, address, phone_country_code, phone_number, email, 
    created_at, updated_at 
FROM users 
WHERE email = $1 AND deleted_at IS NULL
`

type FindUserByEmailRow struct {
	ID                   int64
	IdentificationType   string
	IdentificationNumber string
	FirstName            string
	LastName             string
	BirthDate            pgtype.Date
	Address              []byte
	PhoneCountryCode     string
	PhoneNumber          string
	Email                pgtype.Text
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) FindUserByEmail(ctx context.Context, email pgtype.Text) (FindUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i FindUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.IdentificationType,
		&i.IdentificationNumber,
		&i.FirstName,
		&i.LastName,
		&i.BirthDate,
		&i.Address,
		&i.PhoneCountryCode,
		&i.PhoneNumber,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT 
    id, identification_type, identification_number, first_name, last_name, 
    birth_date, address, phone_country_code, phone_number, email, 
    created_at, updated_at 
FROM users 
WHERE id = $1 AND deleted_at IS NULL
`

type FindUserByIDRow struct {
	ID                   int64
	IdentificationType   string
	IdentificationNumber string
	FirstName            string
	LastName             string
	BirthDate            pgtype.Date
	Address              []byte
	PhoneCountryCode     string
	PhoneNumber          string
	Email                pgtype.Text
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) FindUserByID(ctx context.Context, id int64) (FindUserByIDRow, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i FindUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.IdentificationType,
		&i.IdentificationNumber,
		&i.FirstName,
		&i.LastName,
		&i.BirthDate,
		&i.Address,
		&i.PhoneCountryCode,
		&i.PhoneNumber,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByPhone = `-- name: FindUserByPhone :one
SELECT 
    id, identification_type, identification_number, first_name, last_name, 
    birth_date, address, phone_country_code, phone_number, email, 
    created_at, updated_at 
FROM users 
WHERE phone_country_code = $1 AND phone_number = $2 AND deleted_at IS NULL
`

type FindUserByPhoneParams struct {
	PhoneCountryCode string
	PhoneNumber      string
}

type FindUserByPhoneRow struct {
	ID                   int64
	IdentificationType   string
	IdentificationNumber string
	FirstName            string
	LastName             string
	BirthDate            pgtype.Date
	Address              []byte
	PhoneCountryCode     string
	PhoneNumber          string
	Email                pgtype.Text
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) FindUserByPhone(ctx context.Context, arg FindUserByPhoneParams) (FindUserByPhoneRow, error) {
	row := q.db.QueryRow(ctx, findUserByPhone, arg.PhoneCountryCode, arg.PhoneNumber)
	var i FindUserByPhoneRow
	err := row.Scan(
		&i.ID,
		&i.IdentificationType,
		&i.IdentificationNumber,
		&i.FirstName,
		&i.LastName,
		&i.BirthDate,
		&i.Address,
		&i.PhoneCountryCode,
		&i.PhoneNumber,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUsersPaginatedWithCursor = `-- name: FindUsersPaginatedWithCursor :many
SELECT 
    id, identification_type, identification_number, first_name, last_name, 
    birth_date, address, phone_country_code, phone_number, email, 
    created_at, updated_at 
FROM users 
WHERE id > $1 AND deleted_at IS NULL 
ORDER BY id ASC 
LIMIT $2
`

type FindUsersPaginatedWithCursorParams struct {
	ID    int64
	Limit int32
}

type FindUsersPaginatedWithCursorRow struct {
	ID                   int64
	IdentificationType   string
	IdentificationNumber string
	FirstName            string
	LastName             string
	BirthDate            pgtype.Date
	Address              []byte
	PhoneCountryCode     string
	PhoneNumber          string
	Email                pgtype.Text
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) FindUsersPaginatedWithCursor(ctx context.Context, arg FindUsersPaginatedWithCursorParams) ([]FindUsersPaginatedWithCursorRow, error) {
	rows, err := q.db.Query(ctx, findUsersPaginatedWithCursor, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindUsersPaginatedWithCursorRow
	for rows.Next() {
		var i FindUsersPaginatedWithCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.IdentificationType,
			&i.IdentificationNumber,
			&i.FirstName,
			&i.LastName,
			&i.BirthDate,
			&i.Address,
			&i.PhoneCountryCode,
			&i.PhoneNumber,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findUsersPaginatedWithoutCursor = `-- name: FindUsersPaginatedWithoutCursor :many
SELECT 
    id, identification_type, identification_number, first_name, last_name, 
    birth_date, address, phone_country_code, phone_number, email, 
    created_at, updated_at 
FROM users 
WHERE deleted_at IS NULL 
ORDER BY id ASC 
LIMIT $1
`

type FindUsersPaginatedWithoutCursorRow struct {
	ID                   int64
	IdentificationType   string
	IdentificationNumber string
	FirstName            string
	LastName             string
	BirthDate            pgtype.Date
	Address              []byte
	PhoneCountryCode     string
	PhoneNumber          string
	Email                pgtype.Text
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) FindUsersPaginatedWithoutCursor(ctx context.Context, limit int32) ([]FindUsersPaginatedWithoutCursorRow, error) {
	rows, err := q.db.Query(ctx, findUsersPaginatedWithoutCursor, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindUsersPaginatedWithoutCursorRow
	for rows.Next() {
		var i FindUsersPaginatedWithoutCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.IdentificationType,
			&i.IdentificationNumber,
			&i.FirstName,
			&i.LastName,
			&i.BirthDate,
			&i.Address,
			&i.PhoneCountryCode,
			&i.PhoneNumber,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET 
    identification_type = $1, 
    identification_number = $2, 
    first_name = $3, 
    last_name = $4, 
    birth_date = $5, 
    address = $6, 
    phone_country_code = $7, 
    phone_number = $8, 
    email = $9, 
    updated_at = $10 
WHERE id = $11 AND deleted_at IS NULL
`

type UpdateUserParams struct {
	IdentificationType   string
	IdentificationNumber string
	FirstName            string
	LastName             string
	BirthDate            pgtype.Date
	Address              []byte
	PhoneCountryCode     string
	PhoneNumber          string
	Email                pgtype.Text
	UpdatedAt            pgtype.Timestamptz
	ID                   int64
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.IdentificationType,
		arg.IdentificationNumber,
		arg.FirstName,
		arg.LastName,
		arg.BirthDate,
		arg.Address,
		arg.PhoneCountryCode,
		arg.PhoneNumber,
		arg.Email,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
