// Code generated by mockery v2.53.6. DO NOT EDIT.

package application

import (
	context "context"

	domain "github.com/jdgonzalez907/saas-api/internal/auth/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockRequestOTP is an autogenerated mock type for the RequestOTP type
type MockRequestOTP struct {
	mock.Mock
}

type MockRequestOTP_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRequestOTP) EXPECT() *MockRequestOTP_Expecter {
	return &MockRequestOTP_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, phoneNumber
func (_m *MockRequestOTP) Execute(ctx context.Context, phoneNumber string) (*domain.AuthOTP, error) {
	ret := _m.Called(ctx, phoneNumber)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *domain.AuthOTP
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.AuthOTP, error)); ok {
		return rf(ctx, phoneNumber)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.AuthOTP); ok {
		r0 = rf(ctx, phoneNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AuthOTP)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, phoneNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRequestOTP_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockRequestOTP_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - phoneNumber string
func (_e *MockRequestOTP_Expecter) Execute(ctx interface{}, phoneNumber interface{}) *MockRequestOTP_Execute_Call {
	return &MockRequestOTP_Execute_Call{Call: _e.mock.On("Execute", ctx, phoneNumber)}
}

func (_c *MockRequestOTP_Execute_Call) Run(run func(ctx context.Context, phoneNumber string)) *MockRequestOTP_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRequestOTP_Execute_Call) Return(_a0 *domain.AuthOTP, _a1 error) *MockRequestOTP_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRequestOTP_Execute_Call) RunAndReturn(run func(context.Context, string) (*domain.AuthOTP, error)) *MockRequestOTP_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRequestOTP creates a new instance of MockRequestOTP. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRequestOTP(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRequestOTP {
	mock := &MockRequestOTP{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
