// Code generated by mockery v2.53.6. DO NOT EDIT.

package application

import (
	context "context"

	domain "github.com/jdgonzalez907/saas-api/internal/auth/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockVerifyOTP is an autogenerated mock type for the VerifyOTP type
type MockVerifyOTP struct {
	mock.Mock
}

type MockVerifyOTP_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVerifyOTP) EXPECT() *MockVerifyOTP_Expecter {
	return &MockVerifyOTP_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, sessionID, code
func (_m *MockVerifyOTP) Execute(ctx context.Context, sessionID string, code string) (*domain.User, error) {
	ret := _m.Called(ctx, sessionID, code)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.User, error)); ok {
		return rf(ctx, sessionID, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.User); ok {
		r0 = rf(ctx, sessionID, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, sessionID, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVerifyOTP_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockVerifyOTP_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
//   - code string
func (_e *MockVerifyOTP_Expecter) Execute(ctx interface{}, sessionID interface{}, code interface{}) *MockVerifyOTP_Execute_Call {
	return &MockVerifyOTP_Execute_Call{Call: _e.mock.On("Execute", ctx, sessionID, code)}
}

func (_c *MockVerifyOTP_Execute_Call) Run(run func(ctx context.Context, sessionID string, code string)) *MockVerifyOTP_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockVerifyOTP_Execute_Call) Return(_a0 *domain.User, _a1 error) *MockVerifyOTP_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVerifyOTP_Execute_Call) RunAndReturn(run func(context.Context, string, string) (*domain.User, error)) *MockVerifyOTP_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVerifyOTP creates a new instance of MockVerifyOTP. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVerifyOTP(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVerifyOTP {
	mock := &MockVerifyOTP{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
