// Code generated by mockery. DO NOT EDIT.

package application

import (
	context "context"
	domain "jdgonzalez907/saas-api/internal/users/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockChangeUserEmailUseCase is an autogenerated mock type for the ChangeUserEmailUseCase type
type MockChangeUserEmailUseCase struct {
	mock.Mock
}

type MockChangeUserEmailUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChangeUserEmailUseCase) EXPECT() *MockChangeUserEmailUseCase_Expecter {
	return &MockChangeUserEmailUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, id, email, userID
func (_m *MockChangeUserEmailUseCase) Execute(ctx context.Context, id int64, email *domain.Email, userID int64) error {
	ret := _m.Called(ctx, id, email, userID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *domain.Email, int64) error); ok {
		r0 = rf(ctx, id, email, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChangeUserEmailUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockChangeUserEmailUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - email *domain.Email
//   - userID int64
func (_e *MockChangeUserEmailUseCase_Expecter) Execute(ctx interface{}, id interface{}, email interface{}, userID interface{}) *MockChangeUserEmailUseCase_Execute_Call {
	return &MockChangeUserEmailUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, id, email, userID)}
}

func (_c *MockChangeUserEmailUseCase_Execute_Call) Run(run func(ctx context.Context, id int64, email *domain.Email, userID int64)) *MockChangeUserEmailUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(*domain.Email), args[3].(int64))
	})
	return _c
}

func (_c *MockChangeUserEmailUseCase_Execute_Call) Return(_a0 error) *MockChangeUserEmailUseCase_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChangeUserEmailUseCase_Execute_Call) RunAndReturn(run func(context.Context, int64, *domain.Email, int64) error) *MockChangeUserEmailUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChangeUserEmailUseCase creates a new instance of MockChangeUserEmailUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChangeUserEmailUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChangeUserEmailUseCase {
	mock := &MockChangeUserEmailUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
