// Code generated by mockery. DO NOT EDIT.

package application

import (
	context "context"
	domain "jdgonzalez907/users-api/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockCreateUserUseCase is an autogenerated mock type for the CreateUserUseCase type
type MockCreateUserUseCase struct {
	mock.Mock
}

type MockCreateUserUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateUserUseCase) EXPECT() *MockCreateUserUseCase_Expecter {
	return &MockCreateUserUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, user
func (_m *MockCreateUserUseCase) Execute(ctx context.Context, user *domain.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCreateUserUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockCreateUserUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - user *domain.User
func (_e *MockCreateUserUseCase_Expecter) Execute(ctx interface{}, user interface{}) *MockCreateUserUseCase_Execute_Call {
	return &MockCreateUserUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, user)}
}

func (_c *MockCreateUserUseCase_Execute_Call) Run(run func(ctx context.Context, user *domain.User)) *MockCreateUserUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.User))
	})
	return _c
}

func (_c *MockCreateUserUseCase_Execute_Call) Return(_a0 error) *MockCreateUserUseCase_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCreateUserUseCase_Execute_Call) RunAndReturn(run func(context.Context, *domain.User) error) *MockCreateUserUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCreateUserUseCase creates a new instance of MockCreateUserUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateUserUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateUserUseCase {
	mock := &MockCreateUserUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
