// Code generated by mockery. DO NOT EDIT.

package application

import (
	context "context"
	domain "jdgonzalez907/saas-api/internal/posts/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockCreatePostUseCase is an autogenerated mock type for the CreatePostUseCase type
type MockCreatePostUseCase struct {
	mock.Mock
}

type MockCreatePostUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreatePostUseCase) EXPECT() *MockCreatePostUseCase_Expecter {
	return &MockCreatePostUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, post
func (_m *MockCreatePostUseCase) Execute(ctx context.Context, post *domain.Post) error {
	ret := _m.Called(ctx, post)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Post) error); ok {
		r0 = rf(ctx, post)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCreatePostUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockCreatePostUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - post *domain.Post
func (_e *MockCreatePostUseCase_Expecter) Execute(ctx interface{}, post interface{}) *MockCreatePostUseCase_Execute_Call {
	return &MockCreatePostUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, post)}
}

func (_c *MockCreatePostUseCase_Execute_Call) Run(run func(ctx context.Context, post *domain.Post)) *MockCreatePostUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Post))
	})
	return _c
}

func (_c *MockCreatePostUseCase_Execute_Call) Return(_a0 error) *MockCreatePostUseCase_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCreatePostUseCase_Execute_Call) RunAndReturn(run func(context.Context, *domain.Post) error) *MockCreatePostUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCreatePostUseCase creates a new instance of MockCreatePostUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreatePostUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreatePostUseCase {
	mock := &MockCreatePostUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
