// Code generated by mockery. DO NOT EDIT.

package application

import (
	context "context"
	domain "jdgonzalez907/saas-api/internal/posts/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockFindPostByIDUseCase is an autogenerated mock type for the FindPostByIDUseCase type
type MockFindPostByIDUseCase struct {
	mock.Mock
}

type MockFindPostByIDUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFindPostByIDUseCase) EXPECT() *MockFindPostByIDUseCase_Expecter {
	return &MockFindPostByIDUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, id, authorID
func (_m *MockFindPostByIDUseCase) Execute(ctx context.Context, id int64, authorID int64) (*domain.Post, error) {
	ret := _m.Called(ctx, id, authorID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *domain.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (*domain.Post, error)); ok {
		return rf(ctx, id, authorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) *domain.Post); ok {
		r0 = rf(ctx, id, authorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, id, authorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFindPostByIDUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockFindPostByIDUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - authorID int64
func (_e *MockFindPostByIDUseCase_Expecter) Execute(ctx interface{}, id interface{}, authorID interface{}) *MockFindPostByIDUseCase_Execute_Call {
	return &MockFindPostByIDUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, id, authorID)}
}

func (_c *MockFindPostByIDUseCase_Execute_Call) Run(run func(ctx context.Context, id int64, authorID int64)) *MockFindPostByIDUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockFindPostByIDUseCase_Execute_Call) Return(_a0 *domain.Post, _a1 error) *MockFindPostByIDUseCase_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFindPostByIDUseCase_Execute_Call) RunAndReturn(run func(context.Context, int64, int64) (*domain.Post, error)) *MockFindPostByIDUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFindPostByIDUseCase creates a new instance of MockFindPostByIDUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFindPostByIDUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFindPostByIDUseCase {
	mock := &MockFindPostByIDUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
