// Code generated by mockery. DO NOT EDIT.

package application

import (
	context "context"
	domain "jdgonzalez907/users-api/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockUpdateUserPersonalInformationUseCase is an autogenerated mock type for the UpdateUserPersonalInformationUseCase type
type MockUpdateUserPersonalInformationUseCase struct {
	mock.Mock
}

type MockUpdateUserPersonalInformationUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdateUserPersonalInformationUseCase) EXPECT() *MockUpdateUserPersonalInformationUseCase_Expecter {
	return &MockUpdateUserPersonalInformationUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, id, info
func (_m *MockUpdateUserPersonalInformationUseCase) Execute(ctx context.Context, id int64, info domain.PersonalInformation) error {
	ret := _m.Called(ctx, id, info)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, domain.PersonalInformation) error); ok {
		r0 = rf(ctx, id, info)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUpdateUserPersonalInformationUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockUpdateUserPersonalInformationUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - info domain.PersonalInformation
func (_e *MockUpdateUserPersonalInformationUseCase_Expecter) Execute(ctx interface{}, id interface{}, info interface{}) *MockUpdateUserPersonalInformationUseCase_Execute_Call {
	return &MockUpdateUserPersonalInformationUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, id, info)}
}

func (_c *MockUpdateUserPersonalInformationUseCase_Execute_Call) Run(run func(ctx context.Context, id int64, info domain.PersonalInformation)) *MockUpdateUserPersonalInformationUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(domain.PersonalInformation))
	})
	return _c
}

func (_c *MockUpdateUserPersonalInformationUseCase_Execute_Call) Return(_a0 error) *MockUpdateUserPersonalInformationUseCase_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUpdateUserPersonalInformationUseCase_Execute_Call) RunAndReturn(run func(context.Context, int64, domain.PersonalInformation) error) *MockUpdateUserPersonalInformationUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpdateUserPersonalInformationUseCase creates a new instance of MockUpdateUserPersonalInformationUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdateUserPersonalInformationUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdateUserPersonalInformationUseCase {
	mock := &MockUpdateUserPersonalInformationUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
