// Code generated by mockery. DO NOT EDIT.

package application

import (
	domain "jdgonzalez907/users-api/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockUpdateUserUseCase is an autogenerated mock type for the UpdateUserUseCase type
type MockUpdateUserUseCase struct {
	mock.Mock
}

type MockUpdateUserUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdateUserUseCase) EXPECT() *MockUpdateUserUseCase_Expecter {
	return &MockUpdateUserUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: user
func (_m *MockUpdateUserUseCase) Execute(user *domain.User) error {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.User) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUpdateUserUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockUpdateUserUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - user *domain.User
func (_e *MockUpdateUserUseCase_Expecter) Execute(user interface{}) *MockUpdateUserUseCase_Execute_Call {
	return &MockUpdateUserUseCase_Execute_Call{Call: _e.mock.On("Execute", user)}
}

func (_c *MockUpdateUserUseCase_Execute_Call) Run(run func(user *domain.User)) *MockUpdateUserUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.User))
	})
	return _c
}

func (_c *MockUpdateUserUseCase_Execute_Call) Return(_a0 error) *MockUpdateUserUseCase_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUpdateUserUseCase_Execute_Call) RunAndReturn(run func(*domain.User) error) *MockUpdateUserUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpdateUserUseCase creates a new instance of MockUpdateUserUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdateUserUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdateUserUseCase {
	mock := &MockUpdateUserUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
