// Code generated by mockery. DO NOT EDIT.

package application

import (
	context "context"
	domain "jdgonzalez907/saas-api/internal/posts/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockUpdatePostUseCase is an autogenerated mock type for the UpdatePostUseCase type
type MockUpdatePostUseCase struct {
	mock.Mock
}

type MockUpdatePostUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdatePostUseCase) EXPECT() *MockUpdatePostUseCase_Expecter {
	return &MockUpdatePostUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, id, contentInfo, status, lastEditorID
func (_m *MockUpdatePostUseCase) Execute(ctx context.Context, id int64, contentInfo domain.ContentInformation, status domain.PostStatus, lastEditorID int64) (*domain.Post, error) {
	ret := _m.Called(ctx, id, contentInfo, status, lastEditorID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *domain.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, domain.ContentInformation, domain.PostStatus, int64) (*domain.Post, error)); ok {
		return rf(ctx, id, contentInfo, status, lastEditorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, domain.ContentInformation, domain.PostStatus, int64) *domain.Post); ok {
		r0 = rf(ctx, id, contentInfo, status, lastEditorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, domain.ContentInformation, domain.PostStatus, int64) error); ok {
		r1 = rf(ctx, id, contentInfo, status, lastEditorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpdatePostUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockUpdatePostUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - contentInfo domain.ContentInformation
//   - status domain.PostStatus
//   - lastEditorID int64
func (_e *MockUpdatePostUseCase_Expecter) Execute(ctx interface{}, id interface{}, contentInfo interface{}, status interface{}, lastEditorID interface{}) *MockUpdatePostUseCase_Execute_Call {
	return &MockUpdatePostUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, id, contentInfo, status, lastEditorID)}
}

func (_c *MockUpdatePostUseCase_Execute_Call) Run(run func(ctx context.Context, id int64, contentInfo domain.ContentInformation, status domain.PostStatus, lastEditorID int64)) *MockUpdatePostUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(domain.ContentInformation), args[3].(domain.PostStatus), args[4].(int64))
	})
	return _c
}

func (_c *MockUpdatePostUseCase_Execute_Call) Return(_a0 *domain.Post, _a1 error) *MockUpdatePostUseCase_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpdatePostUseCase_Execute_Call) RunAndReturn(run func(context.Context, int64, domain.ContentInformation, domain.PostStatus, int64) (*domain.Post, error)) *MockUpdatePostUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpdatePostUseCase creates a new instance of MockUpdatePostUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdatePostUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdatePostUseCase {
	mock := &MockUpdatePostUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
