// Code generated by mockery. DO NOT EDIT.

package application

import (
	domain "jdgonzalez907/users-api/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockUpdateUserEmailUseCase is an autogenerated mock type for the UpdateUserEmailUseCase type
type MockUpdateUserEmailUseCase struct {
	mock.Mock
}

type MockUpdateUserEmailUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdateUserEmailUseCase) EXPECT() *MockUpdateUserEmailUseCase_Expecter {
	return &MockUpdateUserEmailUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: id, email
func (_m *MockUpdateUserEmailUseCase) Execute(id int, email *domain.Email) error {
	ret := _m.Called(id, email)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, *domain.Email) error); ok {
		r0 = rf(id, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUpdateUserEmailUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockUpdateUserEmailUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - id int
//   - email *domain.Email
func (_e *MockUpdateUserEmailUseCase_Expecter) Execute(id interface{}, email interface{}) *MockUpdateUserEmailUseCase_Execute_Call {
	return &MockUpdateUserEmailUseCase_Execute_Call{Call: _e.mock.On("Execute", id, email)}
}

func (_c *MockUpdateUserEmailUseCase_Execute_Call) Run(run func(id int, email *domain.Email)) *MockUpdateUserEmailUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(*domain.Email))
	})
	return _c
}

func (_c *MockUpdateUserEmailUseCase_Execute_Call) Return(_a0 error) *MockUpdateUserEmailUseCase_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUpdateUserEmailUseCase_Execute_Call) RunAndReturn(run func(int, *domain.Email) error) *MockUpdateUserEmailUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpdateUserEmailUseCase creates a new instance of MockUpdateUserEmailUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdateUserEmailUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdateUserEmailUseCase {
	mock := &MockUpdateUserEmailUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
