// Code generated by mockery. DO NOT EDIT.

package application

import (
	context "context"
	domain "jdgonzalez907/users-api/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockFindUsersPaginatedUseCase is an autogenerated mock type for the FindUsersPaginatedUseCase type
type MockFindUsersPaginatedUseCase struct {
	mock.Mock
}

type MockFindUsersPaginatedUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFindUsersPaginatedUseCase) EXPECT() *MockFindUsersPaginatedUseCase_Expecter {
	return &MockFindUsersPaginatedUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, pagination
func (_m *MockFindUsersPaginatedUseCase) Execute(ctx context.Context, pagination domain.Pagination) (domain.PaginatedUsers, error) {
	ret := _m.Called(ctx, pagination)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 domain.PaginatedUsers
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Pagination) (domain.PaginatedUsers, error)); ok {
		return rf(ctx, pagination)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Pagination) domain.PaginatedUsers); ok {
		r0 = rf(ctx, pagination)
	} else {
		r0 = ret.Get(0).(domain.PaginatedUsers)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Pagination) error); ok {
		r1 = rf(ctx, pagination)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFindUsersPaginatedUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockFindUsersPaginatedUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - pagination domain.Pagination
func (_e *MockFindUsersPaginatedUseCase_Expecter) Execute(ctx interface{}, pagination interface{}) *MockFindUsersPaginatedUseCase_Execute_Call {
	return &MockFindUsersPaginatedUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, pagination)}
}

func (_c *MockFindUsersPaginatedUseCase_Execute_Call) Run(run func(ctx context.Context, pagination domain.Pagination)) *MockFindUsersPaginatedUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Pagination))
	})
	return _c
}

func (_c *MockFindUsersPaginatedUseCase_Execute_Call) Return(_a0 domain.PaginatedUsers, _a1 error) *MockFindUsersPaginatedUseCase_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFindUsersPaginatedUseCase_Execute_Call) RunAndReturn(run func(context.Context, domain.Pagination) (domain.PaginatedUsers, error)) *MockFindUsersPaginatedUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFindUsersPaginatedUseCase creates a new instance of MockFindUsersPaginatedUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFindUsersPaginatedUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFindUsersPaginatedUseCase {
	mock := &MockFindUsersPaginatedUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
