// Code generated by mockery. DO NOT EDIT.

package application

import (
	context "context"
	domain "jdgonzalez907/users-api/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockFindUserByIdUseCase is an autogenerated mock type for the FindUserByIdUseCase type
type MockFindUserByIdUseCase struct {
	mock.Mock
}

type MockFindUserByIdUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFindUserByIdUseCase) EXPECT() *MockFindUserByIdUseCase_Expecter {
	return &MockFindUserByIdUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, id
func (_m *MockFindUserByIdUseCase) Execute(ctx context.Context, id int) (*domain.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*domain.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *domain.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFindUserByIdUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockFindUserByIdUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockFindUserByIdUseCase_Expecter) Execute(ctx interface{}, id interface{}) *MockFindUserByIdUseCase_Execute_Call {
	return &MockFindUserByIdUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, id)}
}

func (_c *MockFindUserByIdUseCase_Execute_Call) Run(run func(ctx context.Context, id int)) *MockFindUserByIdUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockFindUserByIdUseCase_Execute_Call) Return(_a0 *domain.User, _a1 error) *MockFindUserByIdUseCase_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFindUserByIdUseCase_Execute_Call) RunAndReturn(run func(context.Context, int) (*domain.User, error)) *MockFindUserByIdUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFindUserByIdUseCase creates a new instance of MockFindUserByIdUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFindUserByIdUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFindUserByIdUseCase {
	mock := &MockFindUserByIdUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
