// Code generated by mockery. DO NOT EDIT.

package application

import (
	context "context"
	domain "jdgonzalez907/saas-api/internal/posts/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockFindPostsPaginatedUseCase is an autogenerated mock type for the FindPostsPaginatedUseCase type
type MockFindPostsPaginatedUseCase struct {
	mock.Mock
}

type MockFindPostsPaginatedUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFindPostsPaginatedUseCase) EXPECT() *MockFindPostsPaginatedUseCase_Expecter {
	return &MockFindPostsPaginatedUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, status, pagination
func (_m *MockFindPostsPaginatedUseCase) Execute(ctx context.Context, status domain.PostStatus, pagination domain.Pagination) (domain.PaginatedPosts, error) {
	ret := _m.Called(ctx, status, pagination)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 domain.PaginatedPosts
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PostStatus, domain.Pagination) (domain.PaginatedPosts, error)); ok {
		return rf(ctx, status, pagination)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.PostStatus, domain.Pagination) domain.PaginatedPosts); ok {
		r0 = rf(ctx, status, pagination)
	} else {
		r0 = ret.Get(0).(domain.PaginatedPosts)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.PostStatus, domain.Pagination) error); ok {
		r1 = rf(ctx, status, pagination)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFindPostsPaginatedUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockFindPostsPaginatedUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - status domain.PostStatus
//   - pagination domain.Pagination
func (_e *MockFindPostsPaginatedUseCase_Expecter) Execute(ctx interface{}, status interface{}, pagination interface{}) *MockFindPostsPaginatedUseCase_Execute_Call {
	return &MockFindPostsPaginatedUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, status, pagination)}
}

func (_c *MockFindPostsPaginatedUseCase_Execute_Call) Run(run func(ctx context.Context, status domain.PostStatus, pagination domain.Pagination)) *MockFindPostsPaginatedUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.PostStatus), args[2].(domain.Pagination))
	})
	return _c
}

func (_c *MockFindPostsPaginatedUseCase_Execute_Call) Return(_a0 domain.PaginatedPosts, _a1 error) *MockFindPostsPaginatedUseCase_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFindPostsPaginatedUseCase_Execute_Call) RunAndReturn(run func(context.Context, domain.PostStatus, domain.Pagination) (domain.PaginatedPosts, error)) *MockFindPostsPaginatedUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFindPostsPaginatedUseCase creates a new instance of MockFindPostsPaginatedUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFindPostsPaginatedUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFindPostsPaginatedUseCase {
	mock := &MockFindPostsPaginatedUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
