// Code generated by mockery. DO NOT EDIT.

package application

import (
	context "context"
	domain "jdgonzalez907/saas-api/internal/users/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockChangeUserPhoneUseCase is an autogenerated mock type for the ChangeUserPhoneUseCase type
type MockChangeUserPhoneUseCase struct {
	mock.Mock
}

type MockChangeUserPhoneUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChangeUserPhoneUseCase) EXPECT() *MockChangeUserPhoneUseCase_Expecter {
	return &MockChangeUserPhoneUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, id, phone
func (_m *MockChangeUserPhoneUseCase) Execute(ctx context.Context, id int64, phone domain.Phone) error {
	ret := _m.Called(ctx, id, phone)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, domain.Phone) error); ok {
		r0 = rf(ctx, id, phone)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChangeUserPhoneUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockChangeUserPhoneUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - phone domain.Phone
func (_e *MockChangeUserPhoneUseCase_Expecter) Execute(ctx interface{}, id interface{}, phone interface{}) *MockChangeUserPhoneUseCase_Execute_Call {
	return &MockChangeUserPhoneUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, id, phone)}
}

func (_c *MockChangeUserPhoneUseCase_Execute_Call) Run(run func(ctx context.Context, id int64, phone domain.Phone)) *MockChangeUserPhoneUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(domain.Phone))
	})
	return _c
}

func (_c *MockChangeUserPhoneUseCase_Execute_Call) Return(_a0 error) *MockChangeUserPhoneUseCase_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChangeUserPhoneUseCase_Execute_Call) RunAndReturn(run func(context.Context, int64, domain.Phone) error) *MockChangeUserPhoneUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChangeUserPhoneUseCase creates a new instance of MockChangeUserPhoneUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChangeUserPhoneUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChangeUserPhoneUseCase {
	mock := &MockChangeUserPhoneUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
