// Code generated by mockery. DO NOT EDIT.

package application

import (
	domain "jdgonzalez907/users-api/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockUpdateUserPhoneUseCase is an autogenerated mock type for the UpdateUserPhoneUseCase type
type MockUpdateUserPhoneUseCase struct {
	mock.Mock
}

type MockUpdateUserPhoneUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdateUserPhoneUseCase) EXPECT() *MockUpdateUserPhoneUseCase_Expecter {
	return &MockUpdateUserPhoneUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: id, phone
func (_m *MockUpdateUserPhoneUseCase) Execute(id int, phone domain.Phone) error {
	ret := _m.Called(id, phone)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, domain.Phone) error); ok {
		r0 = rf(id, phone)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUpdateUserPhoneUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockUpdateUserPhoneUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - id int
//   - phone domain.Phone
func (_e *MockUpdateUserPhoneUseCase_Expecter) Execute(id interface{}, phone interface{}) *MockUpdateUserPhoneUseCase_Execute_Call {
	return &MockUpdateUserPhoneUseCase_Execute_Call{Call: _e.mock.On("Execute", id, phone)}
}

func (_c *MockUpdateUserPhoneUseCase_Execute_Call) Run(run func(id int, phone domain.Phone)) *MockUpdateUserPhoneUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(domain.Phone))
	})
	return _c
}

func (_c *MockUpdateUserPhoneUseCase_Execute_Call) Return(_a0 error) *MockUpdateUserPhoneUseCase_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUpdateUserPhoneUseCase_Execute_Call) RunAndReturn(run func(int, domain.Phone) error) *MockUpdateUserPhoneUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpdateUserPhoneUseCase creates a new instance of MockUpdateUserPhoneUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdateUserPhoneUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdateUserPhoneUseCase {
	mock := &MockUpdateUserPhoneUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
