// Code generated by mockery. DO NOT EDIT.

package application

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockDeletePostUseCase is an autogenerated mock type for the DeletePostUseCase type
type MockDeletePostUseCase struct {
	mock.Mock
}

type MockDeletePostUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeletePostUseCase) EXPECT() *MockDeletePostUseCase_Expecter {
	return &MockDeletePostUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, id, authorID
func (_m *MockDeletePostUseCase) Execute(ctx context.Context, id int64, authorID int64) error {
	ret := _m.Called(ctx, id, authorID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, id, authorID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDeletePostUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockDeletePostUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - authorID int64
func (_e *MockDeletePostUseCase_Expecter) Execute(ctx interface{}, id interface{}, authorID interface{}) *MockDeletePostUseCase_Execute_Call {
	return &MockDeletePostUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, id, authorID)}
}

func (_c *MockDeletePostUseCase_Execute_Call) Run(run func(ctx context.Context, id int64, authorID int64)) *MockDeletePostUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockDeletePostUseCase_Execute_Call) Return(_a0 error) *MockDeletePostUseCase_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDeletePostUseCase_Execute_Call) RunAndReturn(run func(context.Context, int64, int64) error) *MockDeletePostUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeletePostUseCase creates a new instance of MockDeletePostUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeletePostUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeletePostUseCase {
	mock := &MockDeletePostUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
