// Code generated by mockery. DO NOT EDIT.

package application

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockDeleteUserUseCase is an autogenerated mock type for the DeleteUserUseCase type
type MockDeleteUserUseCase struct {
	mock.Mock
}

type MockDeleteUserUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeleteUserUseCase) EXPECT() *MockDeleteUserUseCase_Expecter {
	return &MockDeleteUserUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, id
func (_m *MockDeleteUserUseCase) Execute(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDeleteUserUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockDeleteUserUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockDeleteUserUseCase_Expecter) Execute(ctx interface{}, id interface{}) *MockDeleteUserUseCase_Execute_Call {
	return &MockDeleteUserUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, id)}
}

func (_c *MockDeleteUserUseCase_Execute_Call) Run(run func(ctx context.Context, id int64)) *MockDeleteUserUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockDeleteUserUseCase_Execute_Call) Return(_a0 error) *MockDeleteUserUseCase_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDeleteUserUseCase_Execute_Call) RunAndReturn(run func(context.Context, int64) error) *MockDeleteUserUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeleteUserUseCase creates a new instance of MockDeleteUserUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeleteUserUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeleteUserUseCase {
	mock := &MockDeleteUserUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
