// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_application

import (
	"context"

	"github.com/jdgonzalez907/saas-api/internal/users/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockChangeEmail creates a new instance of MockChangeEmail. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChangeEmail(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChangeEmail {
	mock := &MockChangeEmail{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChangeEmail is an autogenerated mock type for the ChangeEmail type
type MockChangeEmail struct {
	mock.Mock
}

type MockChangeEmail_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChangeEmail) EXPECT() *MockChangeEmail_Expecter {
	return &MockChangeEmail_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockChangeEmail
func (_mock *MockChangeEmail) Execute(ctx context.Context, executedBy int64, email domain.Email) (*domain.User, error) {
	ret := _mock.Called(ctx, executedBy, email)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, domain.Email) (*domain.User, error)); ok {
		return returnFunc(ctx, executedBy, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, domain.Email) *domain.User); ok {
		r0 = returnFunc(ctx, executedBy, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, domain.Email) error); ok {
		r1 = returnFunc(ctx, executedBy, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChangeEmail_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockChangeEmail_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - executedBy int64
//   - email domain.Email
func (_e *MockChangeEmail_Expecter) Execute(ctx any, executedBy any, email any) *MockChangeEmail_Execute_Call {
	return &MockChangeEmail_Execute_Call{Call: _e.mock.On("Execute", ctx, executedBy, email)}
}

func (_c *MockChangeEmail_Execute_Call) Run(run func(ctx context.Context, executedBy int64, email domain.Email)) *MockChangeEmail_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 domain.Email
		if args[2] != nil {
			arg2 = args[2].(domain.Email)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockChangeEmail_Execute_Call) Return(user *domain.User, err error) *MockChangeEmail_Execute_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockChangeEmail_Execute_Call) RunAndReturn(run func(ctx context.Context, executedBy int64, email domain.Email) (*domain.User, error)) *MockChangeEmail_Execute_Call {
	_c.Call.Return(run)
	return _c
}
