// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_application

import (
	"context"

	"github.com/jdgonzalez907/saas-api/internal/users/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockChangePhone creates a new instance of MockChangePhone. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChangePhone(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChangePhone {
	mock := &MockChangePhone{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChangePhone is an autogenerated mock type for the ChangePhone type
type MockChangePhone struct {
	mock.Mock
}

type MockChangePhone_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChangePhone) EXPECT() *MockChangePhone_Expecter {
	return &MockChangePhone_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockChangePhone
func (_mock *MockChangePhone) Execute(ctx context.Context, executedBy int64, phone domain.Phone) (*domain.User, error) {
	ret := _mock.Called(ctx, executedBy, phone)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, domain.Phone) (*domain.User, error)); ok {
		return returnFunc(ctx, executedBy, phone)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, domain.Phone) *domain.User); ok {
		r0 = returnFunc(ctx, executedBy, phone)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, domain.Phone) error); ok {
		r1 = returnFunc(ctx, executedBy, phone)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChangePhone_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockChangePhone_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - executedBy int64
//   - phone domain.Phone
func (_e *MockChangePhone_Expecter) Execute(ctx any, executedBy any, phone any) *MockChangePhone_Execute_Call {
	return &MockChangePhone_Execute_Call{Call: _e.mock.On("Execute", ctx, executedBy, phone)}
}

func (_c *MockChangePhone_Execute_Call) Run(run func(ctx context.Context, executedBy int64, phone domain.Phone)) *MockChangePhone_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 domain.Phone
		if args[2] != nil {
			arg2 = args[2].(domain.Phone)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockChangePhone_Execute_Call) Return(user *domain.User, err error) *MockChangePhone_Execute_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockChangePhone_Execute_Call) RunAndReturn(run func(ctx context.Context, executedBy int64, phone domain.Phone) (*domain.User, error)) *MockChangePhone_Execute_Call {
	_c.Call.Return(run)
	return _c
}
