// Code generated by mockery v2.53.6. DO NOT EDIT.

package application

import (
	context "context"

	domain "github.com/jdgonzalez907/saas-api/internal/users/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockChangePhone is an autogenerated mock type for the ChangePhone type
type MockChangePhone struct {
	mock.Mock
}

type MockChangePhone_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChangePhone) EXPECT() *MockChangePhone_Expecter {
	return &MockChangePhone_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, executedBy, phone
func (_m *MockChangePhone) Execute(ctx context.Context, executedBy int64, phone domain.Phone) (*domain.User, error) {
	ret := _m.Called(ctx, executedBy, phone)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, domain.Phone) (*domain.User, error)); ok {
		return rf(ctx, executedBy, phone)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, domain.Phone) *domain.User); ok {
		r0 = rf(ctx, executedBy, phone)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, domain.Phone) error); ok {
		r1 = rf(ctx, executedBy, phone)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChangePhone_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockChangePhone_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - executedBy int64
//   - phone domain.Phone
func (_e *MockChangePhone_Expecter) Execute(ctx interface{}, executedBy interface{}, phone interface{}) *MockChangePhone_Execute_Call {
	return &MockChangePhone_Execute_Call{Call: _e.mock.On("Execute", ctx, executedBy, phone)}
}

func (_c *MockChangePhone_Execute_Call) Run(run func(ctx context.Context, executedBy int64, phone domain.Phone)) *MockChangePhone_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(domain.Phone))
	})
	return _c
}

func (_c *MockChangePhone_Execute_Call) Return(_a0 *domain.User, _a1 error) *MockChangePhone_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChangePhone_Execute_Call) RunAndReturn(run func(context.Context, int64, domain.Phone) (*domain.User, error)) *MockChangePhone_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChangePhone creates a new instance of MockChangePhone. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChangePhone(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChangePhone {
	mock := &MockChangePhone{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
