// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_application

import (
	"context"

	"github.com/jdgonzalez907/saas-api/internal/users/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCreateUser creates a new instance of MockCreateUser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateUser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateUser {
	mock := &MockCreateUser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCreateUser is an autogenerated mock type for the CreateUser type
type MockCreateUser struct {
	mock.Mock
}

type MockCreateUser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateUser) EXPECT() *MockCreateUser_Expecter {
	return &MockCreateUser_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockCreateUser
func (_mock *MockCreateUser) Execute(ctx context.Context, user *domain.User) (*domain.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.User) (*domain.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.User) *domain.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCreateUser_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockCreateUser_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - user *domain.User
func (_e *MockCreateUser_Expecter) Execute(ctx any, user any) *MockCreateUser_Execute_Call {
	return &MockCreateUser_Execute_Call{Call: _e.mock.On("Execute", ctx, user)}
}

func (_c *MockCreateUser_Execute_Call) Run(run func(ctx context.Context, user *domain.User)) *MockCreateUser_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.User
		if args[1] != nil {
			arg1 = args[1].(*domain.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreateUser_Execute_Call) Return(user1 *domain.User, err error) *MockCreateUser_Execute_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockCreateUser_Execute_Call) RunAndReturn(run func(ctx context.Context, user *domain.User) (*domain.User, error)) *MockCreateUser_Execute_Call {
	_c.Call.Return(run)
	return _c
}
