// Code generated by mockery v2.53.6. DO NOT EDIT.

package application

import (
	context "context"

	domain "github.com/jdgonzalez907/saas-api/internal/users/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockFindUserByID is an autogenerated mock type for the FindUserByID type
type MockFindUserByID struct {
	mock.Mock
}

type MockFindUserByID_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFindUserByID) EXPECT() *MockFindUserByID_Expecter {
	return &MockFindUserByID_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, id
func (_m *MockFindUserByID) Execute(ctx context.Context, id int64) (*domain.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*domain.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *domain.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFindUserByID_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockFindUserByID_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockFindUserByID_Expecter) Execute(ctx interface{}, id interface{}) *MockFindUserByID_Execute_Call {
	return &MockFindUserByID_Execute_Call{Call: _e.mock.On("Execute", ctx, id)}
}

func (_c *MockFindUserByID_Execute_Call) Run(run func(ctx context.Context, id int64)) *MockFindUserByID_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockFindUserByID_Execute_Call) Return(_a0 *domain.User, _a1 error) *MockFindUserByID_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFindUserByID_Execute_Call) RunAndReturn(run func(context.Context, int64) (*domain.User, error)) *MockFindUserByID_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFindUserByID creates a new instance of MockFindUserByID. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFindUserByID(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFindUserByID {
	mock := &MockFindUserByID{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
