// Code generated by mockery v2.53.6. DO NOT EDIT.

package application

import (
	context "context"

	domain "github.com/jdgonzalez907/saas-api/internal/users/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockUpdatePersonalInformation is an autogenerated mock type for the UpdatePersonalInformation type
type MockUpdatePersonalInformation struct {
	mock.Mock
}

type MockUpdatePersonalInformation_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdatePersonalInformation) EXPECT() *MockUpdatePersonalInformation_Expecter {
	return &MockUpdatePersonalInformation_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, executedBy, personalInformation
func (_m *MockUpdatePersonalInformation) Execute(ctx context.Context, executedBy int64, personalInformation domain.PersonalInformation) (*domain.User, error) {
	ret := _m.Called(ctx, executedBy, personalInformation)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, domain.PersonalInformation) (*domain.User, error)); ok {
		return rf(ctx, executedBy, personalInformation)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, domain.PersonalInformation) *domain.User); ok {
		r0 = rf(ctx, executedBy, personalInformation)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, domain.PersonalInformation) error); ok {
		r1 = rf(ctx, executedBy, personalInformation)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpdatePersonalInformation_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockUpdatePersonalInformation_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - executedBy int64
//   - personalInformation domain.PersonalInformation
func (_e *MockUpdatePersonalInformation_Expecter) Execute(ctx interface{}, executedBy interface{}, personalInformation interface{}) *MockUpdatePersonalInformation_Execute_Call {
	return &MockUpdatePersonalInformation_Execute_Call{Call: _e.mock.On("Execute", ctx, executedBy, personalInformation)}
}

func (_c *MockUpdatePersonalInformation_Execute_Call) Run(run func(ctx context.Context, executedBy int64, personalInformation domain.PersonalInformation)) *MockUpdatePersonalInformation_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(domain.PersonalInformation))
	})
	return _c
}

func (_c *MockUpdatePersonalInformation_Execute_Call) Return(_a0 *domain.User, _a1 error) *MockUpdatePersonalInformation_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpdatePersonalInformation_Execute_Call) RunAndReturn(run func(context.Context, int64, domain.PersonalInformation) (*domain.User, error)) *MockUpdatePersonalInformation_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpdatePersonalInformation creates a new instance of MockUpdatePersonalInformation. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdatePersonalInformation(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdatePersonalInformation {
	mock := &MockUpdatePersonalInformation{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
